services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - taxmate-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    networks:
      - taxmate-network

networks:
  taxmate-network:
    driver: bridge