version: '3.8'

services:
  frontend:
    build:
      context: .               # Set context to the root of the project
      dockerfile: client/Dockerfile  # Path to your frontend Dockerfile
    ports:
      - "3000:80"               # Map port 3000 on host to port 80 in the container
    depends_on:
      - backend                  # Ensure backend starts before frontend

  backend:
    build:
      context: .                 # Set context to the root of the project
      dockerfile: server/Dockerfile  # Path to your backend Dockerfile
    ports:
      - "5000:5000"              # Map port 5000 on host to port 5000 in the container
    environment:
      FLASK_ENV: production       # Set environment variable for Flask